apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bambu-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  name: {{ .Values.printer.name | quote }}
  ip: {{ .Values.printer.ip | quote }}
  serial: {{ .Values.printer.serial | quote }}
  accessCode: {{ .Values.printer.accessCode | quote }}
